AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  AmazonConnectARN:
    Type: String
    Default: arn:aws:connect:ap-southeast-2:557196841318:instance/44e0f9aa-7f5b-4adc-8e0a-46455c38b400
    Description: Enter the amazon connect entire arn.
Resources:
  personalContactFlow:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "PhoneNumber"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "PhoneNumber"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      Tags:
        - Key: Solution
          Value: 'Sample-Solution'
        - Key: Product
          Value: 'AWS CX'
        - Key: Application
          Value: 'AWS Connect'
Outputs:
  DynamoDBResource:
    Description: "DynamoDB table"
    Value: !Ref personalContactFlow
    Export:
      Name: !Sub "${AWS::StackName}-ddb-table-name"
